// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bank_on_api.Models.Entities.BankOn;

#nullable disable

namespace bank_on_api.Migrations
{
    [DbContext(typeof(BankOn))]
    [Migration("20221205092602_bank_on")]
    partial class bank_on
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("bank_on_api.Models.Entities.BankOn.FinanceProduct", b =>
                {
                    b.Property<Guid>("FinanceProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("AmountMin")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("TermMin")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("_Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("FinanceProductId");

                    b.ToTable("FinanceProduct", "bank_on");
                });

            modelBuilder.Entity("bank_on_api.Models.Entities.BankOn.FinanceRequest", b =>
                {
                    b.Property<Guid>("FinanceRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("AmountRequired")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("DateOfApplication")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("FinanceProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FinanceRequestStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mobile")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Term")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("_Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("FinanceRequestId");

                    b.HasIndex("FinanceProductId");

                    b.HasIndex("FinanceRequestStatusId");

                    b.ToTable("FinanceRequest", "bank_on");
                });

            modelBuilder.Entity("bank_on_api.Models.Entities.BankOn.FinanceRequestLog", b =>
                {
                    b.Property<Guid>("FinanceRequestLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("FinanceRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("_Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("FinanceRequestLogId");

                    b.HasIndex("FinanceRequestId");

                    b.ToTable("FinanceRequestLog", "bank_on");
                });

            modelBuilder.Entity("bank_on_api.Models.Entities.BankOn.FinanceRequestStatus", b =>
                {
                    b.Property<Guid>("FinanceRequestStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("_Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("_case")
                        .HasColumnType("int");

                    b.HasKey("FinanceRequestStatusId");

                    b.ToTable("FinanceRequestStatus", "bank_on");
                });

            modelBuilder.Entity("bank_on_api.Models.Entities.BankOn.FinanceRequest", b =>
                {
                    b.HasOne("bank_on_api.Models.Entities.BankOn.FinanceProduct", "FinanceProduct")
                        .WithMany("FinanceRequest")
                        .HasForeignKey("FinanceProductId")
                        .HasConstraintName("fk_finance_product_finance_request_1");

                    b.HasOne("bank_on_api.Models.Entities.BankOn.FinanceRequestStatus", "FinanceRequestStatus")
                        .WithMany("FinanceRequest")
                        .HasForeignKey("FinanceRequestStatusId")
                        .HasConstraintName("fk_finance_request_status_finance_request_1");

                    b.Navigation("FinanceProduct");

                    b.Navigation("FinanceRequestStatus");
                });

            modelBuilder.Entity("bank_on_api.Models.Entities.BankOn.FinanceRequestLog", b =>
                {
                    b.HasOne("bank_on_api.Models.Entities.BankOn.FinanceRequest", "FinanceRequest")
                        .WithMany("FinanceRequestLog")
                        .HasForeignKey("FinanceRequestId")
                        .HasConstraintName("fk_finance_request_finance_request_log_1");

                    b.Navigation("FinanceRequest");
                });

            modelBuilder.Entity("bank_on_api.Models.Entities.BankOn.FinanceProduct", b =>
                {
                    b.Navigation("FinanceRequest");
                });

            modelBuilder.Entity("bank_on_api.Models.Entities.BankOn.FinanceRequest", b =>
                {
                    b.Navigation("FinanceRequestLog");
                });

            modelBuilder.Entity("bank_on_api.Models.Entities.BankOn.FinanceRequestStatus", b =>
                {
                    b.Navigation("FinanceRequest");
                });
#pragma warning restore 612, 618
        }
    }
}
